# 应用服务 WEB 访问端口
server:
  port: 8081

#数据库数据源的配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/bin_text?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true

#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.wsj.medical2025.pojo #类的别名
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
  mapper-locations: classpath*:/mapper/*.xml #sql映射文件的位置


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径,输入http:localhost:8080/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs    #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs:
    - group: 'default'   #分组名称
      paths-to-match: '/**'   #配置需要匹配的路径,默认为/**
      packages-to-scan: com.wsj.medical2025    #配置要扫描包的路径,一般配置到启动类所在的包名
#packages-to-scan一定要记得修改-------------------------------------------------------------------

# knife4j的增强配置，不需要增强可以不配(建议配置一下)
knife4j:
  enable: true    #开启knife4j,无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文
    swagger-model-name: 实体类列表   #重命名SwaggerModel名称,默认

swagger3:
  name: wsj团队
  email: whiskeyaka9@gmail.com
  title: 慧医数字应用系统
  description: 慧医数字应用系统后端API接口
  version: 1.0
  termsOfServiceUrl: https://www.baidu.com